dev:
  mongodb:
    primary:
      url: cluster0.euo7rfd.mongodb.net
      port: 27017
      username: yuna
      password: mvZ1bRNbxPvFdRPp
  express:
    primary:
      location: http://localhost
      port: 5002
  image_server:
    primary:
      location: http://kdt-sw-7-team09.elicecoding.com
      port: 3007
prod:
  mongodb:
    primary:
      url:
      port:
  express:
    primary:
      port:
  image_server:
    primary:
      location: http://kdt-sw-7-team09.elicecoding.com
      port: 3007
