dev:
  mongodb:
    primary:
      url: sinbad0.p0s7gq5.mongodb.net
      port: 27017
      username: sinba_d
      password: 1BOwsXly9gByCVUF
  express:
    primary:
      location: http://localhost
      port: 8080
prod:
  mongodb:
    primary:
      url:
      port:
  express:
    primary:
      port:
