dev:
  image_server:
    primary:
      location: http://kdt-sw-7-team09.elicecoding.com
      port: 3007
prod:
  image_server:
    primary:
      location: http://kdt-sw-7-team09.elicecoding.com
      port: 3007
