dev:
  image_server:
    primary:
      location: http://kdt-sw-7-team09.elicecoding.com
      port: 8080
prod:
  image_server:
    primary:
      location: http://kdt-sw-7-team09.elicecoding.com
      port: 8080
